# _config.yml
title: Truong Nguyen's Portfolio
description: Portfolio website for Truong Nguyen - Data Scientist & Machine Learning Engineer
theme: minima

# Add the following line to include the custom CSS
include:
  - assets/css/styles.css