# _config.yml
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Truong Nguyen's Portfolio
description: Portfolio website for Truong Nguyen - Data Scientist & Machine Learning Engineer
show_downloads: false

github:
  is_project_page: false